<a href="https://colab.research.google.com/github/chswapnil/Machine-Learning/blob/main/ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.4.0'

In [3]:
datasheet = pd.read_csv('Churn_Modelling.csv');
x = datasheet.iloc[:,3:-1].values;
y = datasheet.iloc[:,-1].values;

In [4]:
print(x);

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


Label Encoding used for Relational Data

In [5]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder();
x[:,2] = le.fit_transform(x[:,2]);

In [6]:
print(x)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


Hot Encoding of Unrelational Data

In [8]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])],remainder='passthrough');
x = np.array(ct.fit_transform(x));

In [9]:
print(x);

[[1.0 0.0 1.0 ... 1 1 101348.88]
 [1.0 0.0 0.0 ... 0 1 112542.58]
 [1.0 0.0 1.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 1.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 1.0 ... 1 0 38190.78]]


Splitting Training set and Test set

In [11]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_test, y_train = train_test_split(x, y, test_size=0.2,random_state=0);

Feature Scaling

In [12]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler();
x_train = sc.fit_transform(x_train);
x_test = sc.transform(x_test);

Initialization of ANN

In [15]:
ann = tf.keras.models.Sequential();

Adding Input Layer and first hidden Layer

In [16]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'));

Adding the second hidden layer

In [17]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'));