<a href="https://colab.research.google.com/github/chswapnil/Machine-Learning/blob/main/ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [90]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [91]:
tf.__version__

'2.4.0'

In [92]:
datasheet = pd.read_csv('Churn_Modelling.csv');
x = datasheet.iloc[:,3:-1].values;
y = datasheet.iloc[:,-1].values;

In [93]:
print(x);

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


Label Encoding used for Relational Data

In [94]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder();
x[:,2] = le.fit_transform(x[:,2]);

In [95]:
print(x)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


Hot Encoding of Unrelational Data

In [96]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])],remainder='passthrough');
x = np.array(ct.fit_transform(x));

In [97]:
print(x);

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


Splitting Training set and Test set

In [98]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2,random_state=0);

Feature Scaling

In [99]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler();
x_train = sc.fit_transform(x_train);
x_test = sc.transform(x_test);

Initialization of ANN

In [100]:
ann = tf.keras.models.Sequential();

Adding Input Layer and first hidden Layer

In [101]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'));

Adding the second hidden layer

In [102]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'));

Adding the output layer

In [103]:
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'));

Training the ANN

Compiling the ANN

In [104]:
ann.compile(optimizer= 'adam', loss= 'binary_crossentropy', metrics=['accuracy'] );

Training the ANN on the Training set

In [105]:
ann.fit(x_train,y_train,batch_size=32, epochs=100);

Epoch 1/100
250/250 [==============================] - 1s 923us/step - loss: 0.6238 - accuracy: 0.6581
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4673 - accuracy: 0.8032
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4216 - accuracy: 0.8127
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4137 - accuracy: 0.8212
Epoch 5/100
250/250 [==============================] - 0s 977us/step - loss: 0.4043 - accuracy: 0.8218
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3900 - accuracy: 0.8312
Epoch 7/100
250/250 [==============================] - 0s 973us/step - loss: 0.3876 - accuracy: 0.8309
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3939 - accuracy: 0.8287
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3845 - accuracy: 0.8339
Epoch 10/100
250/250 [==============================] - 0s 982us/step - loss: 0.3820 